### ISSUE TITLE
Grafana and Prometheus setup on AWS for Univa

### ISSUE THREAD

**Issue by aupadh12** [UnivaCorporation/unisight-visualizations#12]
Hello,

I have my Prometheus and Grafana setup running on kubernetes containers in AWS EKS. I have installed Univa data bridge v2.0.0 on an RHEL EC2 machine and our unisight server is also in the same AWS account but on another EC2 instance.
Can you please let me know how can I modify the setup to forward the data from unisight data bridge to the Prometheus and Grafana running on EKS. Do I need to run unisight data bridge also as a container for making this architecture work?

**Comment by aupadh12** [comment]
This issue is now fixed since I had to use a different graphql url.

**Comment by aupadh12** [comment]
Any update on this?

**Comment by cameronbrunner** [comment]
I assume you have moved past using this project but I wanted to have an answer for this open ticket:

In this architecture prometheus pulls data from the data bridge to build metrics that can be consumed by grafana.  In your setup you would need to update:

https://github.com/UnivaCorporation/unisight-visualizations/blob/master/prometheus/docker/prometheus/prometheus.yml#L24 

line to point to your unisight data bridge.  Your EKS prometheus install should be able to initiate this connection but you would need to open up the security group your unisight server is using to allow inbound connections from your EKS instances.  I would expect you would have them in the same VPC or in peered VPCs.  If you don't you would have to expose a public IP on your unisight server or have a NAT with a port forwarding rule to allow the inbound prometheus connection.

**Comment by cameronbrunner** [comment]
I will leave this open for at least 30 days before closing it.
